### PR TITLE
2fixed: Notes timestamp & hide VideoFab when doubt/note is created

### LINKED ISSUE #770: While creating notes the timestamp is not correct
**Describe the bug**
While creating notes the timestamp is not correct and changes by higher margin even if the "add note" clicked again after one second

**To Reproduce**
1. Go to 'Any Video Lecture'
2. Click on 'Add note'
3. Scroll down to 'Check the timestamp'
4. It dosen't match with actual video time at that instance.

**Expected behavior**
The timestamp should actually matched with the video time at that instance

**Screenshots**
Screenshot (58)
Screenshot (60)
Screenshot (61)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 6 pro|
|Android Version|Android Pie|

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by shivamgohri**
Fixes #770  #772 

Changes: 
1) Whenever a note/doubt is successfully created, videoFab will be hidden.
2) Notes timestamp is corrected.

Screenshots for the change:
Hide VideoFab:
note_boss

Notes Timestamp:
notetime_boss

### CODE REVIEW

**Comment by shivamgohri** [comment]
@aggarwalpulkit596 review?

**Comment by aggarwalpulkit596** [comment]
@shivamgohri will take a look in few hours

**Comment by shivamgohri** [comment]
@aggarwalpulkit596 ?

**Comment by shivamgohri** [comment]
@aggarwalpulkit596

**Review by aggarwalpulkit596 — APPROVED** [review]

**Pull request merged**
