### PR TITLE
Edit Text added to Notes in Library to edit the note on click

### LINKED ISSUE #754: Add editText to every Notes
**Inside Course->Library->Notes . it shows whole notes in a page .
we can add onClickListener to each note to read and edit the notes .
**
Implement onclickListener to each note and Implement functionality to edit and read notes in separate Activity ..

**Screenshots**

Screenshot_2020-05-16-07-04-59-071_com codingblocks cbonlineapp

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by prathamk22**
Fixes #754 

Changes: Added a edit text to changed the note from My Notes in Library

Screenshots for the change:
WhatsApp Image 2020-06-26 at 18 07 47

### CODE REVIEW

**Comment by prathamk22** [comment]
@aggarwalpulkit596 pls review this sir.

**Comment by aggarwalpulkit596** [comment]
it should be done via a edit button

**Comment by prathamk22** [comment]
@aggarwalpulkit596 changes done

**Comment by aggarwalpulkit596** [comment]
@prathamk22 screenshot for the same?

**Comment by aggarwalpulkit596** [comment]
also, can you make sure when items are being deleted we cannot edit anything

**Comment by prathamk22** [comment]
@aggarwalpulkit596 
While deleting notes, When user clicks on any other note it is being selected and user is not able to click that edit button while selection tracker is activated. So it is handled already.

WhatsApp Image 2020-06-28 at 13 16 53

**Comment by aggarwalpulkit596** [comment]
Add test for edit note

**Comment by prathamk22** [comment]
@aggarwalpulkit596 sir but no API is introduced into this? just test the previous API only?

**Comment by aggarwalpulkit596** [comment]
Yes but we intend to keep tests for everything now

**Comment by prathamk22** [comment]
@aggarwalpulkit596 test added for fetch notes

**Comment by prathamk22** [comment]
@aggarwalpulkit596 added test for fetch notes

**Pull request merged**
