### PR TITLE
feat: show marked answers in BottomSheet in Quiz

### LINKED ISSUE #146: show marked question in quiz sheet
**Describe the feature you'd like**
Show marked items in the quiz bottom similar to web

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #146 

Changes: 
- bottom sheet in quiz fragment reflects the questions with chosen answers

Screenshots for the change:
https://drive.google.com/open?id=1-B0PPVyk5uPuTCq2DnUb0mYXCX0Ezq0x

### CODE REVIEW

**Comment by adityastic** [comment]
@aggarwalpulkit596 review

**Comment by aggarwalpulkit596** [comment]
This is for the submitted quiz?

**Comment by adityastic** [comment]
@aggarwalpulkit596 not yet, It currently only marks the questions answered. So you want to show the correct and non correct answers when submitted right?

**Comment by adityastic** [comment]
@aggarwalpulkit596 I've updated the pr. It now shows the correct answers rather than the marked answers when the quiz is in submitted state. Uploaded a video for the same :) :
https://drive.google.com/open?id=1-B0PPVyk5uPuTCq2DnUb0mYXCX0Ezq0x

**Comment by aggarwalpulkit596** [comment]
You've handled both the cases ? Submitted quiz as well as draft quiz ?

**Comment by adityastic** [comment]
@aggarwalpulkit596 yes please check the video. I've shown both as well

**Comment by adityastic** [comment]
@aggarwalpulkit596 do I need to update anything in this?

**Comment by aggarwalpulkit596** [comment]
Nicely Done @adityastic

**Comment by adityastic** [comment]
@aggarwalpulkit596 all thanks to you 😊

**Pull request merged**
