### PR TITLE
Added free with proper layout

### LINKED ISSUE #164: Add free label to free section of trial course in My Course Activity

### PR DESCRIPTION
**Pull request by shubhamofbce**
Fixes  #164 

Changes: 1. Changed the title layout orientation from centre to top
                 2. Added free label 

Screenshots for the change:
free with layout

### CODE REVIEW

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 have a last look at this screenshot and try to merge.

**Comment by aggarwalpulkit596** [comment]
It should have a some top margin as well doesn't look good

**Comment by shubhamofbce** [comment]
Is this looking fine @aggarwalpulkit596 
removed the minimum hieght of the section content block which was= 60dp earlier
and gave 5dp margin from top and bottom too.
if it is alright then i will send anew pr for it.
margin 23may

**Comment by aggarwalpulkit596** [comment]
Squash your commits don't make a new PR

**Comment by aggarwalpulkit596** [comment]
And why can't min height be used along with this ?

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 this was the reason to remove min. hieght
minium hieght was set as 60 dp which was more enough too wrap the content for 80% of the tiles
and due to that there was a lot of space empty at bottom which was again not looking good

**Comment by aggarwalpulkit596** [comment]
Squash your commits read contributing guidelines if you're unable to do it

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 I squashed all the commits into one commit . Now the app is looking like this 
margin 23may

.

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 Sorry to disturb you again but please revert this PR since it has a 
It showing free everywhere in the course details page in the recomended course part. This error arised since it was using the same section content file.
BUG2
BUG1

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 i am ready with its solution 
Just removed the text free from the text view and bind it through kotlin
nowworking

**Comment by aggarwalpulkit596** [comment]
I've already pushed an fix for this

**Comment by shubhamofbce** [comment]
Thanks a lot for this @aggarwalpulkit596 I learned a lot from you. You are a real mentor.

**Pull request merged**
