### PR TITLE
fix: Issue in "Delete all Downloads" Confirmation Prompt

### LINKED ISSUE #879: Bug report : Issue in "Delete all Downloads" Confirmation Prompt.
#### Description of the bug :bug: 
It shows the same confirmation prompt while deleting all downloads even if there is nothing to delete.

**To Reproduce**
1. Go to setting 
2. Make sure that you have no downloaded yet, if there, then delete all downloads.
3. Tap on Delete all downloads.
4. It will again show confirmation for download.
5. But there is nothing to delete.

**Expected behavior**

It should prompt  "**No downloads**" instead of this confirmation prompt.

**Screenshots**

 

Since the used space is **0MB** than also it showing the same prompt.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by mrwhoknows55**
Fixes #879

Changes:
Added `isSomethingDownloaded` boolean which is responsible to change the visibility of `Delete All Textview` Button.   

Screenshots for the change:
deleted
Old

### CODE REVIEW

**Comment by mrwhoknows55** [comment]
@aggarwalpulkit596 please review. How to  solve `Build: Unit Tests Failing` issue?

**Comment by aggarwalpulkit596** [comment]
@mrwhoknows55 token have been expired I'll update it with a constant one in few days

**Comment by mrwhoknows55** [comment]
Ok

**Comment by mrwhoknows55** [comment]
@aggarwalpulkit596  How to solve tests failing issue?

**Comment by aggarwalpulkit596** [comment]
@mrwhoknows55 you can avoid the lint test for now, I'll be fixing the unit test and apk thing in a few minutes

**Comment by mrwhoknows55** [comment]
@aggarwalpulkit596 any changes required?

**Pull request closed without merging**
