### PR TITLE
Fixed the problem of download button

### PR DESCRIPTION
**Pull request by mohitpanwar09**
Fixes #[873]

Changes: [Made a call to the deletFile() function so that if we again click on the download button it shows an dialog box showing warning that "This lecture will be deleted !!!" ]

Screenshots for the change:

### CODE REVIEW

**Comment by mohitpanwar09** [comment]
@aggarwalpulkit596 bhaiya how to resolve this test case which is failing

**Comment by aggarwalpulkit596** [comment]
merge your pr with the latest develop

**Comment by mohitpanwar09** [comment]
@aggarwalpulkit596  bhaiya now please take a look

**Comment by mohitpanwar09** [comment]
@aggarwalpulkit596 bhaiya please take a look

**Comment by aggarwalpulkit596** [comment]
@mohitpanwar09 can you share a working video?

**Comment by mohitpanwar09** [comment]
ezgif com-video-to-gif

**Comment by mohitpanwar09** [comment]
@aggarwalpulkit596 now if we again click on the downloaded lecture it will pop up a message that " this lecture will be deleted !!!" 
previously the call for the delete function was not made.

**Comment by aggarwalpulkit596** [comment]
It looks nice but can you match the theme which is being used for dialog ?

**Pull request closed without merging**
