### PR TITLE
Learning Tracks Chips Horizontal Scroll added

### LINKED ISSUE #661: Make Chip Group Horizontally Scrollable
Item Track Card consist a Chip group for multiple career options chips. It's not scrollable when multiple chip items arrise.
gif

### PR DESCRIPTION
**Pull request by prathamk22**
Fixes #661 

Added a Horizontal Scroll View as a parent to the com.google.android.material.chip.ChipGroup which makes multiple childs scroll horizontally

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
Always add screenshot/gif for visual changes

**Comment by prathamk22** [comment]
> Always add screenshot/gif for visual changes

Sometimes it show multiple chips and sometimes not, so I was not able to take the screenshot. I tested it with adding multiple chips through code and it is working. Should I add that screenshot if you want?

**Comment by prathamk22** [comment]
@aggarwalpulkit596 can you pls review it?

**Comment by prathamk22** [comment]
See Python web development chips:

Before Scroll
WhatsApp Image 2020-05-24 at 10 38 31

After Scroll:
WhatsApp Image 2020-05-24 at 10 38 31 (1)

**Review by aggarwalpulkit596 — APPROVED** [review]

**Pull request merged**
