### PR TITLE
Updated/Removed OutOfBound Errors with low space android/Solved Internet Issue/

### PR DESCRIPTION
**Pull request by gptshubham595**
Removed ClearText line though many a time its a reason for internet browse error but due to security breach removed that

### CODE REVIEW

**Comment by sarthak-1998** [comment]
@aggarwalpulkit596  please verify !

**Comment by aggarwalpulkit596** [comment]
Resolve conflicts and squash your commits

**Comment by gptshubham595** [comment]
@aggarwalpulkit596  no problem I am closing and again opening this

**Comment by gptshubham595** [comment]
#492 check this

**Pull request closed without merging**
