### PR TITLE
Clear Cart Functionality added in CheckoutOrderDetailsFragment

### LINKED ISSUE #665: Remove Course from Cart.
**Describe the feature you'd like**
In CheckoutDetailsFragmnet there should be a button to **remove the current item** or **clear cart**. 

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by hardik-dua**
Fixes #665 

Changes: Clear Cart Functionality added in CheckoutOrderDetailsFragment

Screenshot_2020-05-11-10-15-30-71

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
Always add screenshots in which visual changes are done

**Comment by hardik0899** [comment]
> Always add screenshots in which visual changes are d

> Always add screenshots in which visual changes are done

Ok Next time I will take care of this.

**Comment by hardik-dua** [comment]
Ok Next time I will take care of this. @aggarwalpulkit596

**Comment by iamspathan** [comment]
@hardik0899  Have a look at dukaan.codingblocks.com cart remove feature. There is one API call  to `https://dukaan.codingblocks.com/mycart/removeproduct"` which removes the current course from the cart when **Remove Product** button clicked
Screenshot (38)

**Comment by hardik-dua** [comment]
@iamspathan Sir I have done this similar thing only. Dukan allows one course at one time in the cart therefore we only need a single API call to clear the cart. I have also made an API call to remove that product from the cart and its working.I have not used any external resource, only used the api that I found in RespApi in online api module. If one clears the cart from android it too is cleared from the website also for that account i have verified and tested this.

**Comment by hardik0899** [comment]
Oh Okay you want me to make UI exactly similar as of the dukan webpage. means instead of clear I have

**Comment by hardik-dua** [comment]
Ok @iamspathan I will change the UI from clear button to remove product button as similar to the dukan's website and will commit the changes in this PR itself.

**Comment by hardik-dua** [comment]
UI updated.. and changes commited

**Comment by aggarwalpulkit596** [comment]
Screenshot 2020-05-11 at 10 31 13 AM
Actually i need something like this so probably need a new fragment for this

**Comment by aggarwalpulkit596** [comment]
Any Updates on this @hardik0899

**Comment by hardik-dua** [comment]
@aggarwalpulkit596 I have made the functionality similar to as of the website as shown above in my screen shot. Its looking replica as of website and working fine too.

**Comment by aggarwalpulkit596** [comment]
> Screenshot 2020-05-11 at 10 31 13 AM
> 
> Actually i need something like this so probably need a new fragment for this
This has been to done like this also on clearing cart empty view should get visible

**Comment by hardik-dua** [comment]
Ok

**Comment by hardik-dua** [comment]
> > Screenshot 2020-05-11 at 10 31 13 AM
> > Actually i need something like this so probably need a new fragment for this
> > This has been to done like this also on clearing cart empty view should get visible

is this fragment already available there on the app and I just have to add remove product functionality??

**Comment by aggarwalpulkit596** [comment]
No this one has to be created I'll increase the bounties as there will be much more work required now

**Comment by hardik-dua** [comment]
> No this one has to be created I'll increase the bounties as there will be much more work required now

@aggarwalpulkit596 Ok Sir I am trying to make this functionality. Once I make a PR for this you can assign the bounties as per the work done.

**Comment by aggarwalpulkit596** [comment]
@hardik0899 yes i will

**Comment by aggarwalpulkit596** [comment]
Any updates on this @hardik0899

**Comment by hardik-dua** [comment]
Sir I would like that you better assign this issue to somebody else.. due to my ongoing internship I can only contribute to small issues.. This one seems somewhat hectic.. Sorry :(

**Comment by hardik-dua** [comment]
> Sir I would like that you better assign this issue to somebody else.. due to my ongoing internship I can only contribute to small issues.. This one seems somewhat hectic.. Sorry :(

Else my previous PR is working awesome if that functionality is Ok than merge this one.

**Comment by aggarwalpulkit596** [comment]
Can you just resolve the conflicts issue and share a gif of entire process

**Comment by hardik-dua** [comment]
Ok Will do that in few minutes

**Comment by hardik-dua** [comment]
This video size was too much so I attached it through Email as well as
conflicts resolved and build successfully made through codebeats.

**Comment by hardik-dua** [comment]
20200516-215644-720x1280




GIF for the feature added as well as conflicts resolved. Please have a look @aggarwalpulkit596 Sir. Its very much replica of the website.

**Review by aggarwalpulkit596 — APPROVED** [review]

**Pull request merged**
