### PR TITLE
fix: video crash when youtube video

### PR DESCRIPTION
**Pull request by adityastic**
Fixes video view for youtube

### CODE REVIEW

**Comment by adityastic** [comment]
@aggarwalpulkit596 here is the fix

**Comment by adityastic** [comment]
@aggarwalpulkit596 OnlineAPI test failed, Please Check the Server

**Comment by aggarwalpulkit596** [comment]
JWT token would have been invalidated by now replace the token with yours token for now will add test token for future

**Comment by adityastic** [comment]
@aggarwalpulkit596 was afk, updated

**Comment by adityastic** [comment]
@aggarwalpulkit596 failed again

**Comment by aggarwalpulkit596** [comment]
Failing because token credentials does not match with the request id's

**Pull request merged**
