### PR TITLE
Updated #697

### LINKED ISSUE #697: Clicking Explore Courses textview in Cart doesn't open up Explore fragment
**Describe the bug**

When the user is in any fragment other than explore courses fragment, and opens cart and clicks on explore courses textview, it returns to same fragment.

**To Reproduce**

Clicking **Explore Courses** should return to **Explore** fragment.

**Screenshots**

Screenshot_20200514-154432_(Debug)Coding Blocks
Screenshot_20200514-154434_(Debug)Coding Blocks

I'm uploading the screenshot for the time when I am on doubts fragment and clicks on cart icon and then explore courses textview and then it returns to doubts fragment.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galxy M30s|
|Android Version|Android 10|

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by adiig7**
Fixes #697 

**Changes:** 
Changed the onClick for *Explore Courses*

Screenshots for the change:

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
There is a particular method to open activity kindly use that and also in case of logged-in user he will be redirected to dashboard fragment to keep that one in mind too

**Comment by adiig7** [comment]
@aggarwalpulkit596  sir even if a user is logged in, if there are no courses in the cart he/she needs to explore courses, therefore it should jump to explore courses not dashboard.

**Comment by aggarwalpulkit596** [comment]
> @aggarwalpulkit596 sir even if a user is logged in, if there are no courses in the cart he/she needs to explore courses, therefore it should jump to explore courses not dashboard.

Yes, so you need to fix that and use the method which is used everywhere to open dashboard activity

**Comment by adiig7** [comment]
@aggarwalpulkit596 sir i dont think you are getting my point, imagine a user is logged in, if his cart is empty, and explore courses is clicked so he needs to be redirected to explore fragment not dashboard because he needs to find some courses to buy, so that part I think is good and talking about the method to open activity, I'll change that.

**Comment by aggarwalpulkit596** [comment]
I'm getting your point but if you the method that i'm telling you about you will be redirected to the dashboard instead of home page so you need to handle that part if you're logged in

**Comment by adiig7** [comment]
But @aggarwalpulkit596 sir you need to explore courses not go to dashboard even if the user is logged in. I tried my code with logged in and logged out, and it redirects to *Explore*, why do we even need to redirect to *Dashboard* if we have to explore courses to add to the cart.

**Comment by aggarwalpulkit596** [comment]
First, check how I am navigating to dashboard activity from other activities for instance just check splash activity

**Comment by aggarwalpulkit596** [comment]
@adiig7 any updates?

**Comment by adiig7** [comment]
@aggarwalpulkit596 I'll be working on it today will chnge it asap.

**Comment by adiig7** [comment]
@aggarwalpulkit596 sir I tried startActivity the same way you have done in SplashActivity, and it redirects to Dashboard fragment, is that the way you want?

**Comment by aggarwalpulkit596** [comment]
It should be done in that way although you can additional paramaters so that you set which fragment should be opened

**Pull request closed without merging**
