### PR TITLE
fixed: Courses Certificate Description

### LINKED ISSUE #762: All courses Certificate show same title
**Describe the bug**
All course certificates show the same title "Complete 90% of the course to unlock certificate"
However, the Threshold Completion varies in the content of the certificate!

**To Reproduce**
1. Go to 'Any Course'
2. Scroll down to 'Generate Certificate'
3. Do this for many courses, you will see the error!

**Expected behavior**
Every certificate should be made personalized and should show the same text as content of the certificate.

**Screenshots**
InkedScreenshot_20200516-183708_LI
InkedScreenshot_20200516-183716_LI

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Oneplus 6|
|Android Version|Android 10|

**Additional context**

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by shivamgohri**
Fixes #762
Fixed the issue "All courses certificate show same description"

Changes: 
1) For each course, the completion threshold will be displayed in the Certificate Description Tv

Screenshots for the change:
Screenshot_20200516-210901
Screenshot_20200516-210853

### CODE REVIEW

**Comment by shivamgohri** [comment]
wait, more changes needs to be made!

**Comment by shivamgohri** [comment]
@aggarwalpulkit596 check this! It is working but these checks are not completed, why so?

**Comment by hardik-dua** [comment]
> @aggarwalpulkit596 check this! It is working but these checks are not completed, why so?

@shivamgohri bro some PR's are open since tuesday and checks have'nt completed yet. Don't know why does codebeat took so much time.

**Comment by shivamgohri** [comment]
@hardik0899 Are you talking about my code? and PR?

**Comment by hardik-dua** [comment]
@shivamgohri no bro I was just in general saying just see this https://github.com/coding-blocks/CBOnlineApp/pull/680 its checks are yet to be completed but it was open 4 days ago

**Comment by shivamgohri** [comment]
@aggarwalpulkit596 review please?

**Comment by shivamgohri** [comment]
Will work again on it! 
:(

**Pull request closed without merging**
