### PR TITLE
feat: picture in picture mode 

### LINKED ISSUE #291: Implement Picture in picture mode in the app
**Describe the feature you'd like**
For videoactivity there should be a picture in picture mode

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by raystatic**
Fixes #291 

Changes: implemented picture in picture mode in video player activity

Screenrecording for the change:
fix_pip

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
Did you handle user permissions as well ?

**Comment by aggarwalpulkit596** [comment]
Also make a settings button to open android settings to disable pip similiar to swiggy implementation

**Comment by aggarwalpulkit596** [comment]
Update on this?

**Comment by raystatic** [comment]
Into something.. will do it tomorrow

**Comment by aggarwalpulkit596** [comment]
Rebase your PR

**Pull request closed without merging**
