### PR TITLE
Added Empty Doubts View

### LINKED ISSUE #663: Add empty view for doubts in video player

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #663 

Changes: Added Empty Doubts view.

Screenshots for the change:

> Cannot capture screenshot from the app as app screen doesn't allow that

### CODE REVIEW

**Comment by jddeep** [comment]
@aggarwalpulkit596 Reviews please. Also didn't quite get the reason for build failure here :thinking:

**Comment by jddeep** [comment]
@aggarwalpulkit596 Fixed Builds here as well :)

**Comment by aggarwalpulkit596** [comment]
Current UI doesn't align with the theme kindly make it similar as the empty
notes view also there is gradient icon for doubts use that.

**Comment by aggarwalpulkit596** [comment]
Screenshot_20200518-203337

**Comment by aggarwalpulkit596** [comment]
Current UI doesn't align with the theme kindly make it similar as the empty notes view also there is a gradient icon for doubts use that.
Screenshot_20200518-203320
Screenshot_20200518-203337

**Comment by jddeep** [comment]
@aggarwalpulkit596 Have a look now

**Comment by aggarwalpulkit596** [comment]
Can you add some screenshot ? Xml layout screenshot would do if you are not able take the screenshot

**Comment by jddeep** [comment]
@aggarwalpulkit596 Have a look ss added. Should I increase the size of the image a bit more?

**Comment by aggarwalpulkit596** [comment]
Make it similar to the notes empty view

**Comment by jddeep** [comment]
@aggarwalpulkit596 done

**Review by aggarwalpulkit596 — APPROVED** [review]

**Pull request merged**
