### PR TITLE
feat: Download limit in Settings

### LINKED ISSUE #217: Add Download Limit in Settings
Add A Limit in Settings to for downloading videos preferably a slider with a minimum of 1GB max Up to 10GB

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #217 

Changes: 
- added download limit for videos

Screenshots for the change:
https://drive.google.com/open?id=1-9UtcPkO2t4bwTCfsiqi5hHzHYIZH-qS

### CODE REVIEW

**Comment by adityastic** [comment]
@aggarwalpulkit596 please review. I've uploaded a video for the same.

**Comment by aggarwalpulkit596** [comment]
@adityastic Nice Work Here Will merge this tomorrow

**Comment by adityastic** [comment]
@aggarwalpulkit596 no worries sir, take your time

**Comment by adityastic** [comment]
@aggarwalpulkit596 please take actions on my opened prs

**Pull request merged**
