### PR TITLE
Revert "Shubham1"

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Reverts coding-blocks/CBOnlineApp#187

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@shubhamofbce reverting this as this is not working at all
device-2019-05-18-234935

**Comment by shubhamofbce** [comment]
Is it taking some time to load or is not working at all??
I hope it is taking some time to load then its alright.
It was not taking that small time too when there was no text in TextView You suggested to keep The text FREE in the TextView after that it gets a bit slower.

**Comment by aggarwalpulkit596** [comment]
It's showing free for all the sections but only top two sections are free in this course

**Comment by shubhamofbce** [comment]
In my phone it is working fine, It is just taking a little time to load.
working fine

**Comment by aggarwalpulkit596** [comment]
Tried with multiple courses not working

**Comment by shubhamofbce** [comment]
ok

**Comment by aggarwalpulkit596** [comment]
@shubhamofbce i just checked your code your logic is incorrect it won't work at all at any cost you aren't even checking whether the section is premium or not

**Comment by shubhamofbce** [comment]
I am sorry, I won't be able to work on this anymore . You can give this task to anyone else.

**Pull request merged**
