### PR TITLE
[WIP]Course activity Added

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@championswimmer @the-dagger any ideas for course page? the above implementation  look too clustered, I was thinking of implementing collapsing toolbar

**Comment by aggarwalpulkit596** [comment]
videotogif_2018 09 23_13 21 21

**Comment by aggarwalpulkit596** [comment]
videotogif_2018 09 23_13 32 23

**Comment by aggarwalpulkit596** [comment]
screenshot-1538081429821
Design for Horizontal Cards

**Comment by championswimmer** [comment]
in horizontal cards, remove the explore button, make the entire card clickable instead

**Comment by aggarwalpulkit596** [comment]
Okay Bhaiya 👍

**Comment by aggarwalpulkit596** [comment]
screenshot-1538239453721
@championswimmer is the design for sections is okay or should i add something to the layout

**Comment by aggarwalpulkit596** [comment]
@championswimmer the design for expandable layout is okay ?

**Comment by championswimmer** [comment]
looks good for now, we'll ask designer to provided updated components for smaller things like this later

**Comment by championswimmer** [comment]
I am merging this, looks good for now, we can continue work in another PR

**Pull request merged**
