### PR TITLE
enhancement: change download check logic

### LINKED ISSUE #243: Change Video Downloaded Logic
Current Logic mark a video downloaded if the user downloads the video instead it should check system files if that folder exists

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #243 

Changes: 
- Downloads are not checked on isDownloaded now. It checks if the file is present or not

### CODE REVIEW

**Comment by adityastic** [comment]
@aggarwalpulkit596 check

**Comment by aggarwalpulkit596** [comment]
But what's when the file download is in progress

**Comment by adityastic** [comment]
@aggarwalpulkit596 updated

**Comment by aggarwalpulkit596** [comment]
But this will fail if somehow db is destructed or updated and boolean value is set to false again

**Comment by adityastic** [comment]
@aggarwalpulkit596 If it failed we would not even have the sectionList, so therefore we would not reach this condition at all, hence that condition is redundant. And Updating and setting the boolean to false again, No Other applications have access to other apps data partition other than the case where the user is rooted. But thats a problem for every application.

**Comment by aggarwalpulkit596** [comment]
Build Travis and circle ci first in a seperate PR

**Comment by adityastic** [comment]
> Build Travis and circle ci first in a seperate PR

Done

**Comment by adityastic** [comment]
@aggarwalpulkit596 resolved conflicts in this as well

**Comment by adityastic** [comment]
@aggarwalpulkit596 please give an update on this as well

**Comment by adityastic** [comment]
@aggarwalpulkit596 please have a look

**Comment by adityastic** [comment]
@aggarwalpulkit596 resolved conflicts and fixed spotless

**Comment by adityastic** [comment]
@aggarwalpulkit596 it has been over a month to this as well. Please finalize this

**Comment by adityastic** [comment]
@aggarwalpulkit596 pulkit I claimed 200 bounty for this as well, if you agree I can make up for refractoring issue in this claim?

**Pull request closed without merging**
