### PR TITLE
Adding Spotlight

### LINKED ISSUE #854: Add app demo using Spotlight
References
https://github.com/TakuSemba/Spotlight

### PR DESCRIPTION
**Pull request by AkshobhyaP**
Fixes #854 

Uses TapTarget Library to create a walkthrough of the application.

Screenshots

### CODE REVIEW

**Comment by AkshobhyaP** [comment]
@aggarwalpulkit596 please review.

**Comment by aggarwalpulkit596** [comment]
You would be required to add more spotlights specially for a course

**Comment by AkshobhyaP** [comment]
Can you please give some more details, like for any of my enrolled course or for any course in the catalog.

**Comment by aggarwalpulkit596** [comment]
Yes add some of it in your enrolled courses and also add for video playback

**Comment by aggarwalpulkit596** [comment]
@AkshobhyaP any updates on this ?

**Comment by AkshobhyaP** [comment]
@aggarwalpulkit596 please review.

**Comment by aggarwalpulkit596** [comment]
@AkshobhyaP can you resolve the conflicts also make sure that you run ktlint --F on files that you are changing/modifying

**Comment by AkshobhyaP** [comment]
There is some issue with squashing the commits, I am opening a new pr.

**Pull request closed without merging**
