### PR TITLE
Issue722

### LINKED ISSUE #722: Search is not working
**Describe the bug**
Seacrh is not working anywhere in the app

**To Reproduce**

1. Go to 'All Courses'
2. Click on 'Click on search box'
3. Scroll down to 'Type some relevant text'
4. Click on search icon - Nothing will happen.

**Expected behavior**
Search should work .

**Screenshots**
isue2

**Smartphone Info:**

|Device         |Redmi 5a|
|Android Version|android 7.1 |

**Additional context**
Search should work if this feature is given

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by prince-09**
Fixes https://github.com/coding-blocks/CBOnlineApp/issues/722 Have called the initial functions of calling the API. Some API problem is there it is not returning any value "findCourse" is called.

Changes: added the function for calling the API which will make everything ok when API problem is solved.

### CODE REVIEW

**Comment by prince-09** [comment]
@aggarwalpulkit596 is findCourse API is working fine?

**Comment by aggarwalpulkit596** [comment]
Yes api are working fine

**Comment by prince-09** [comment]
> Yes api are working fine

Can you give me URL for findCourse API here?

**Comment by aggarwalpulkit596** [comment]
You can get it from the website
Bdw this API is already implemented in the app and you have to use that one but feel free to check the website first

**Pull request closed without merging**
