### PR TITLE
Added submit button in Quiz Bottom Sheet.

### PR DESCRIPTION
**Pull request by thedevelopersanjeev**
Fixes part 5 of #181 

Changes: Added submit button in quiz bottom sheet

Screenshots for the change:
Screenshot_20190519-002154

### CODE REVIEW

**Comment by thedevelopersanjeev** [comment]
@aggarwalpulkit596  should I keep the button here or add it in hidden view of the bottom sheet?
and
what should be done on clicking the submit button?
a.) Submit the quiz directly and move to the quiz result screen.
or
b.) Display a message showing that the quiz has not been completed yet.

**Comment by aggarwalpulkit596** [comment]
First of all Rebase and squash your PR and hide it in the bottom sheet and show a confirmation before submitting the quiz and then show result screen fix Transition animation as well

**Comment by thedevelopersanjeev** [comment]
After reverting my last commit, I am in sync with the main repository. Now, how to rebase and squash above 13 commits which are appearing in this PR.
I have read some articles but still, find it confusing. : (
Can you help me out @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
First read this
https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository
then this
https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

**Pull request closed without merging**
