### PR TITLE
Update CourseActivity.kt

### PR DESCRIPTION
**Pull request by chetan767**
Course Share link is '404 NOT FOUND' #701

Solved

### CODE REVIEW

**Comment by chetan767** [comment]
WhatsApp Image 2020-05-15 at 1 40 41 AM

**Comment by aggarwalpulkit596** [comment]
This URL is not being captured in the app you need to modify things so that it is captured by the app as well

**Comment by aggarwalpulkit596** [comment]
https://online.codingblocks.com/courses/c-plus-plus-online-course-for-beginners something like this

**Comment by aggarwalpulkit596** [comment]
@chetan767 can you rename PR that makes more sense what are you doing in this exactly

**Pull request closed without merging**
