### PR TITLE
Addeed Free label this time with proper logic

### LINKED ISSUE #164: Add free label to free section of trial course in My Course Activity

### PR DESCRIPTION
**Pull request by shubhamofbce**
Fixes #164 

Changes: Added free label to all the data that are not premium.
Logic: If Data is not premium visibility gone otherwise show free.

Screenshots for the change:
I think this time it will work for sure.
Cp course that is paid
ML course unapaid

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
Fix Conflicts Rest LGTM

**Comment by shubhamofbce** [comment]
Conflicts fixed

**Comment by aggarwalpulkit596** [comment]
Travis is failing

**Comment by shubhamofbce** [comment]
I am new to github so can you please help me resolve these checks i don't know much about these @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
open Travis and scroll to bottom of the page  there will be an error message

**Pull request closed without merging**
